name: tests

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5   # installs Python & caches pip
      with:
        python-version: "3.12"
        cache: "pip"                  # built-in cache for requirements.txt  :contentReference[oaicite:0]{index=0}
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Run pytest
      run: pytest -q
